### PR TITLE
Add related modules and bump babel

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by iamstarkov** [comment]
can you tell me more about babel-register thing, did they extract babel-core/register into separate package?

**Comment by ghost** [comment]
yes, they separated core and [require hook](http://babeljs.io/docs/usage/require/)

**Comment by iamstarkov** [comment]
babel is waaay too fast

**Comment by iamstarkov** [comment]
thank you very much

**Comment by iamstarkov** [comment]
merged and published as well

**Pull request merged**
